import { ItemCategory, ItemDefinition } from './types';

export const ITEM_DEFINITIONS: ItemDefinition[] = [
  // --- FISH & ANIMALS (Swim) ---
  { id: 'goldfish', emoji: '🐠', name: 'Goldie', category: ItemCategory.FISH, defaultScale: 1.5, movement: 'swim' },
  { id: 'tropical', emoji: '🐟', name: 'Blue Tang', category: ItemCategory.FISH, defaultScale: 1.2, movement: 'swim' },
  { id: 'puffer', emoji: '🐡', name: 'Puffer', category: ItemCategory.FISH, defaultScale: 1.3, movement: 'swim' },
  { id: 'shark', emoji: '🦈', name: 'Shark', category: ItemCategory.FISH, defaultScale: 2.2, movement: 'swim' },
  { id: 'whale', emoji: '🐋', name: 'Whale', category: ItemCategory.FISH, defaultScale: 3.5, movement: 'swim' },
  { id: 'dolphin', emoji: '🐬', name: 'Dolphin', category: ItemCategory.FISH, defaultScale: 2.5, movement: 'swim' },
  { id: 'squid', emoji: '🦑', name: 'Squid', category: ItemCategory.FISH, defaultScale: 1.4, movement: 'float' },
  { id: 'octopus', emoji: '🐙', name: 'Octopus', category: ItemCategory.FISH, defaultScale: 1.6, movement: 'crawl' },
  { id: 'shrimp', emoji: '🦐', name: 'Shrimp', category: ItemCategory.FISH, defaultScale: 0.8, movement: 'crawl' },
  { id: 'crab', emoji: '🦀', name: 'Crab', category: ItemCategory.FISH, defaultScale: 1, movement: 'crawl' },
  { id: 'lobster', emoji: '🦞', name: 'Lobster', category: ItemCategory.FISH, defaultScale: 1.2, movement: 'crawl' },
  { id: 'croc', emoji: '🐊', name: 'Croc', category: ItemCategory.FISH, defaultScale: 2, movement: 'swim' },
  { id: 'turtle', emoji: '🐢', name: 'Turtle', category: ItemCategory.FISH, defaultScale: 1.4, movement: 'swim' },
  { id: 'lizard', emoji: '🦎', name: 'Newt', category: ItemCategory.FISH, defaultScale: 0.9, movement: 'crawl' },
  { id: 'snake', emoji: '🐍', name: 'Sea Snake', category: ItemCategory.FISH, defaultScale: 1.3, movement: 'swim' },
  { id: 'duck', emoji: '🦆', name: 'Rubber Duck', category: ItemCategory.FISH, defaultScale: 1.2, movement: 'float' },
  { id: 'swan', emoji: '🦢', name: 'Swan', category: ItemCategory.FISH, defaultScale: 2, movement: 'float' },
  { id: 'penguin', emoji: '🐧', name: 'Penguin', category: ItemCategory.FISH, defaultScale: 1.3, movement: 'swim' },
  { id: 'seal', emoji: '🦭', name: 'Seal', category: ItemCategory.FISH, defaultScale: 2, movement: 'swim' },
  { id: 'otter', emoji: '🦦', name: 'Otter', category: ItemCategory.FISH, defaultScale: 1.5, movement: 'float' },
  { id: 'microbe', emoji: '🦠', name: 'Plankton', category: ItemCategory.FISH, defaultScale: 0.5, movement: 'float' },
  { id: 'snail', emoji: '🐌', name: 'Sea Snail', category: ItemCategory.FISH, defaultScale: 0.6, movement: 'crawl' },
  { id: 'butterfly', emoji: '🦋', name: 'Sea Moth', category: ItemCategory.FISH, defaultScale: 0.8, movement: 'swim' },
  { id: 'dragon', emoji: '🐉', name: 'Sea Dragon', category: ItemCategory.FISH, defaultScale: 3, movement: 'swim' },
  { id: 'sauropod', emoji: '🦕', name: 'Nessie', category: ItemCategory.FISH, defaultScale: 4, movement: 'swim' },

  // --- PLANTS (Sway) ---
  { id: 'herb', emoji: '🌿', name: 'Tall Grass', category: ItemCategory.PLANT, defaultScale: 2, movement: 'sway' },
  { id: 'seaweed', emoji: '🌾', name: 'Seaweed', category: ItemCategory.PLANT, defaultScale: 2, movement: 'sway' },
  { id: 'kelp', emoji: '🥬', name: 'Leafy Kelp', category: ItemCategory.PLANT, defaultScale: 1.5, movement: 'sway' },
  { id: 'hibiscus', emoji: '🌺', name: 'Sea Flower', category: ItemCategory.PLANT, defaultScale: 1.2, movement: 'sway' },
  { id: 'bamboo', emoji: '🎍', name: 'Bamboo', category: ItemCategory.PLANT, defaultScale: 2.2, movement: 'sway' },
  { id: 'palm', emoji: '🌴', name: 'Mini Palm', category: ItemCategory.PLANT, defaultScale: 2.5, movement: 'sway' },
  { id: 'cactus', emoji: '🌵', name: 'Sea Cactus', category: ItemCategory.PLANT, defaultScale: 1.5, movement: 'none' },
  { id: 'mushroom', emoji: '🍄', name: 'Toadstool', category: ItemCategory.PLANT, defaultScale: 1, movement: 'none' },
  { id: 'rose', emoji: '🌹', name: 'Red Rose', category: ItemCategory.PLANT, defaultScale: 1, movement: 'sway' },
  { id: 'sunflower', emoji: '🌻', name: 'Sun Flower', category: ItemCategory.PLANT, defaultScale: 1.5, movement: 'sway' },
  { id: 'lotus', emoji: '🪷', name: 'Lotus', category: ItemCategory.PLANT, defaultScale: 1.3, movement: 'float' },
  { id: 'maple', emoji: '🍁', name: 'Red Leaf', category: ItemCategory.PLANT, defaultScale: 1, movement: 'float' },
  { id: 'fallen', emoji: '🍂', name: 'Brown Leaf', category: ItemCategory.PLANT, defaultScale: 1, movement: 'float' },
  { id: 'tree', emoji: '🌳', name: 'Bonsai', category: ItemCategory.PLANT, defaultScale: 2, movement: 'none' },
  { id: 'pine', emoji: '🌲', name: 'Pine', category: ItemCategory.PLANT, defaultScale: 2, movement: 'none' },
  { id: 'seedling', emoji: '🌱', name: 'Sprout', category: ItemCategory.PLANT, defaultScale: 0.8, movement: 'sway' },
  { id: 'shamrock', emoji: '☘️', name: 'Clover', category: ItemCategory.PLANT, defaultScale: 0.8, movement: 'sway' },
  { id: 'tulip', emoji: '🌷', name: 'Tulip', category: ItemCategory.PLANT, defaultScale: 1.2, movement: 'sway' },
  { id: 'blossom', emoji: '🌸', name: 'Cherry', category: ItemCategory.PLANT, defaultScale: 1, movement: 'sway' },
  { id: 'bouquet', emoji: '💐', name: 'Bouquet', category: ItemCategory.PLANT, defaultScale: 1.5, movement: 'none' },

  // --- DECOR (Mostly None or Float) ---
  { id: 'rock', emoji: '🪨', name: 'Rock', category: ItemCategory.DECOR, defaultScale: 1.5, movement: 'none' },
  { id: 'wood', emoji: '🪵', name: 'Driftwood', category: ItemCategory.DECOR, defaultScale: 1.8, movement: 'none' },
  { id: 'shell', emoji: '🐚', name: 'Conch Shell', category: ItemCategory.DECOR, defaultScale: 1, movement: 'none' },
  { id: 'coral', emoji: '🪸', name: 'Coral', category: ItemCategory.DECOR, defaultScale: 1.8, movement: 'none' },
  { id: 'anchor', emoji: '⚓', name: 'Anchor', category: ItemCategory.DECOR, defaultScale: 2, movement: 'none' },
  { id: 'amphora', emoji: '🏺', name: 'Ancient Vase', category: ItemCategory.DECOR, defaultScale: 1.5, movement: 'none' },
  { id: 'castle', emoji: '🏰', name: 'Castle', category: ItemCategory.DECOR, defaultScale: 3, movement: 'none' },
  { id: 'gem', emoji: '💎', name: 'Treasure', category: ItemCategory.DECOR, defaultScale: 0.8, movement: 'none' },
  { id: 'moai', emoji: '🗿', name: 'Moai', category: ItemCategory.DECOR, defaultScale: 2, movement: 'none' },
  { id: 'gate', emoji: '⛩️', name: 'Torii Gate', category: ItemCategory.DECOR, defaultScale: 2.5, movement: 'none' },
  { id: 'tokyo', emoji: '🗼', name: 'Tower', category: ItemCategory.DECOR, defaultScale: 2.5, movement: 'none' },
  { id: 'liberty', emoji: '🗽', name: 'Statue', category: ItemCategory.DECOR, defaultScale: 2.5, movement: 'none' },
  { id: 'ufo', emoji: '🛸', name: 'UFO', category: ItemCategory.DECOR, defaultScale: 2, movement: 'float' },
  { id: 'ruin', emoji: '🏚️', name: 'Ruin', category: ItemCategory.DECOR, defaultScale: 2.5, movement: 'none' },
  { id: 'skull', emoji: '☠️', name: 'Skull', category: ItemCategory.DECOR, defaultScale: 1.2, movement: 'none' },
  { id: 'bone', emoji: '🦴', name: 'Bone', category: ItemCategory.DECOR, defaultScale: 1, movement: 'none' },
  { id: 'key', emoji: '🗝️', name: 'Old Key', category: ItemCategory.DECOR, defaultScale: 0.8, movement: 'none' },
  { id: 'box', emoji: '📦', name: 'Crate', category: ItemCategory.DECOR, defaultScale: 1.5, movement: 'none' },
  { id: 'gift', emoji: '🎁', name: 'Gift', category: ItemCategory.DECOR, defaultScale: 1.2, movement: 'none' },
  { id: 'bike', emoji: '🚲', name: 'Sunken Bike', category: ItemCategory.DECOR, defaultScale: 2, movement: 'none' },
  { id: 'car', emoji: '🚗', name: 'Car Wreck', category: ItemCategory.DECOR, defaultScale: 2.5, movement: 'none' },
  { id: 'ship', emoji: '🛳️', name: 'Ship', category: ItemCategory.DECOR, defaultScale: 3, movement: 'none' },
  { id: 'tub', emoji: '🛁', name: 'Bathtub', category: ItemCategory.DECOR, defaultScale: 2, movement: 'none' },
  { id: 'coffin', emoji: '⚰️', name: 'Coffin', category: ItemCategory.DECOR, defaultScale: 1.8, movement: 'none' },
  { id: 'urn', emoji: '⚱️', name: 'Urn', category: ItemCategory.DECOR, defaultScale: 1, movement: 'none' },
  { id: 'hole', emoji: '🕳️', name: 'Black Hole', category: ItemCategory.DECOR, defaultScale: 1.5, movement: 'none' },
  { id: 'volcano', emoji: '🌋', name: 'Volcano', category: ItemCategory.DECOR, defaultScale: 3, movement: 'none' },
  { id: 'hut', emoji: '🛖', name: 'Hut', category: ItemCategory.DECOR, defaultScale: 2.2, movement: 'none' },
  { id: 'tent', emoji: '⛺', name: 'Tent', category: ItemCategory.DECOR, defaultScale: 1.8, movement: 'none' },
  { id: 'fountain', emoji: '⛲', name: 'Fountain', category: ItemCategory.DECOR, defaultScale: 2, movement: 'none' },

  // --- EQUIPMENT ---
  { id: 'bubbler', emoji: '🫧', name: 'Bubbles', category: ItemCategory.EQUIPMENT, defaultScale: 1, movement: 'float' },
  { id: 'light', emoji: '💡', name: 'Spotlight', category: ItemCategory.EQUIPMENT, defaultScale: 1, movement: 'none' },
  { id: 'thermometer', emoji: '🌡️', name: 'Thermo', category: ItemCategory.EQUIPMENT, defaultScale: 1.2, movement: 'float' },
  { id: 'net', emoji: '🕸️', name: 'Net', category: ItemCategory.EQUIPMENT, defaultScale: 1.5, movement: 'none' },
  { id: 'food', emoji: '🥫', name: 'Fish Food', category: ItemCategory.EQUIPMENT, defaultScale: 1, movement: 'float' },
  { id: 'hook', emoji: '🪝', name: 'Hook', category: ItemCategory.EQUIPMENT, defaultScale: 1.2, movement: 'float' },
  { id: 'magnet', emoji: '🧲', name: 'Cleaner', category: ItemCategory.EQUIPMENT, defaultScale: 1, movement: 'crawl' },
  { id: 'sponge', emoji: '🧽', name: 'Sponge', category: ItemCategory.EQUIPMENT, defaultScale: 1, movement: 'none' },
  { id: 'bucket', emoji: '🪣', name: 'Bucket', category: ItemCategory.EQUIPMENT, defaultScale: 1.5, movement: 'none' },
  { id: 'broom', emoji: '🧹', name: 'Broom', category: ItemCategory.EQUIPMENT, defaultScale: 1.5, movement: 'none' },
];
